title: Vicente Castro

# Hosting
domain: vvcastro.github.io
baseurl: "/"
url: https://vvcastro.github.io

# Contact Info
email: vicentejavier.castro@mail.polimi.it
first_name: Vicente
last_name: Castro Solar

description: >
  Academic page!
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.

# -----------------------------------------------------------------------------
# Accounts
# -----------------------------------------------------------------------------
x_username: vvcastro_
github_username: vvcastro
linkedin_username: vvcastros
scholar_userid: # Google Scholar ID
medium_username: # Medium username
research_gate_profile: # ResearchGate
stackoverflow_id: # StackOverflow

contact_note: >
  Feel free to reach out!

# -----------------------------------------------------------------------------
# General Settings
# -----------------------------------------------------------------------------
lang: en

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

# Exclude from processing.
include: ["_pages"]
exclude:
  - bin
  - CONTRIBUTING.md
  - CUSTOMIZE.md
  - docker-compose.yml
  - Dockerfile
  - FAQ.md
  - Gemfile
  - Gemfile.lock
  - INSTALL.md
  - LICENSE
  - package.json
  - package-lock.json
  - purgecss.config.js
  - README.md
  - vendor
keep_files:
  - CNAME
  - .nojekyll

# Theme and design
theme: minima
sass:
  style: compressed
max_width: 800px
full-width: true

# Sitemap settings
defaults:
  - scope:
      path: "assets/**/*.*"
    values:
      sitemap: false

# Plug-ins
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-minifier
  - jekyll-sitemap
  - jekyll-twitter-plugin
  - jekyll-email-protect
  - jekyll-toc
  - jemoji

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

news_limit: 5

# -----------------------------------------------------------------------------
# Jekyll Minifier
# -----------------------------------------------------------------------------
jekyll-minifier:
  exclude: ["robots.txt"]
  uglifier_args:
    harmony: true

# -----------------------------------------------------------------------------
# Library versions
# -----------------------------------------------------------------------------
bootstrap-table:
  version: "1.22.1"
jquery:
  version: "3.6.0"
  integrity: "sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
mathjax:
  version: "3.2.0"
masonry:
  version: "4.2.2"
  integrity: "sha256-Nn1q/fx0H7SNLZMQ5Hw5JLaTRZp0yILA/FRexe19VdI="
mdb:
  version: "4.20.0"
  integrity:
    css: "sha256-jpjYvU3G3N6nrrBwXJoVEYI/0zw8htfFnhT9ljN3JJw="
    js: "sha256-NdbiivsvWt7VYCt6hYNT3h/th9vSTL4EDWeGs5SN3DA="
medium_zoom:
  version: "1.0.8"
  integrity: "sha256-7PhEpEWEW0XXQ0k6kQrPKwuoIomz8R8IYyuU1Qew4P8="
