title: Vicente Castro

# Hosting
domain: vvcastro.github.io
baseurl: ""
url: https://vvcastro.github.io

# Contact Info
email: vicentejavier.castro@mail.polimi.it

description: > # this means to ignore newlines until "baseurl:"
  Academic page!

twitter_username: vvcastro_
github_username: vvcastro

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
